[abstract]
== Executive Summary
{ospver} ({ro} 7) is a reliable infrastructure platform based on
OpenStack. {ro} 7 has a modular service-based architecture designed
for massive scalability. This document describes Red Hat’s approach to
scaling OpenStack with a scalable and resilient network infrastructure.

Benefits of this approach include:

* Greater network bandwidth and capacity
* Network isolation for individual tenants or projects improves
  security
* Network overlay allows overlapping IP address ranges between tenants
  or projects
* Highly available network controllers and network hardware improve
  fault tolerance and resiliency

The first section of this document describes the {ro} 7 architecture
and the highly available network architectures which are recommended
for use with {ro} 7. The second section describes approaches to
networking high availability. The third section describes the lab
environment, hardware, and software versions used to test the
reference architecture. The fourth section describes setting up the
network and deploying OpenStack. The fifth section describes the
OpenStack Neutron configuration of tenant network segregation,
including overlay networks. The sixth section includes some common
troubleshooting techniques for Neutron networks.
